import Foundation

public enum AppCategory: String, CaseIterable, Identifiable, Sendable {
    case none = "none"
    case books = "books"
    case business = "business"
    case developerTools = "developerTools"
    case education = "education"
    case entertainment = "entertainment"
    case finance = "finance"
    case foodAndDrink = "foodAndDrink"
    case games = "games"
    case actionGames = "actionGames"
    case adventureGames = "adventureGames"
    case boardGames = "boardGames"
    case cardGames = "cardGames"
    case casinoGames = "casinoGames"
    case casualGames = "casualGames"
    case familyGames = "familyGames"
    case kidsGames = "kidsGames"
    case musicGames = "musicGames"
    case puzzleGames = "puzzleGames"
    case racingGames = "racingGames"
    case rolePlayingGames = "rolePlayingGames"
    case simulationGames = "simulationGames"
    case sportsGames = "sportsGames"
    case strategyGames = "strategyGames"
    case triviaGames = "triviaGames"
    case wordGames = "wordGames"
    case graphicsAndDesign = "graphicsAndDesign"
    case healthAndFitness = "healthAndFitness"
    case lifestyle = "lifestyle"
    case magazinesAndNewspapers = "magazinesAndNewspapers"
    case medical = "medical"
    case music = "music"
    case navigation = "navigation"
    case news = "news"
    case photography = "photography"
    case productivity = "productivity"
    case reference = "reference"
    case shopping = "shopping"
    case socialNetworking = "socialNetworking"
    case sports = "sports"
    case travel = "travel"
    case utilities = "utilities"
    case video = "video"
    case weather = "weather"
    
    public var id: String { rawValue }
    
    public var displayName: String {
        switch self {
        case .none: return "None"
        case .books: return "Books"
        case .business: return "Business"
        case .developerTools: return "Developer Tools"
        case .education: return "Education"
        case .entertainment: return "Entertainment"
        case .finance: return "Finance"
        case .foodAndDrink: return "Food & Drink"
        case .games: return "Games"
        case .actionGames: return "Games - Action Games"
        case .adventureGames: return "Games - Adventure Games"
        case .boardGames: return "Games - Board Games"
        case .cardGames: return "Games - Card Games"
        case .casinoGames: return "Games - Casino Games"
        case .casualGames: return "Games - Casual Games"
        case .familyGames: return "Games - Family Games"
        case .kidsGames: return "Games - Kids Games"
        case .musicGames: return "Games - Music Games"
        case .puzzleGames: return "Games - Puzzle Games"
        case .racingGames: return "Games - Racing Games"
        case .rolePlayingGames: return "Games - Role Playing Games"
        case .simulationGames: return "Games - Simulation Games"
        case .sportsGames: return "Games - Sports Games"
        case .strategyGames: return "Games - Strategy Games"
        case .triviaGames: return "Games - Trivia Games"
        case .wordGames: return "Games - Word Games"
        case .graphicsAndDesign: return "Graphics & Design"
        case .healthAndFitness: return "Health & Fitness"
        case .lifestyle: return "Lifestyle"
        case .magazinesAndNewspapers: return "Magazines & Newspapers"
        case .medical: return "Medical"
        case .music: return "Music"
        case .navigation: return "Navigation"
        case .news: return "News"
        case .photography: return "Photography"
        case .productivity: return "Productivity"
        case .reference: return "Reference"
        case .shopping: return "Shopping"
        case .socialNetworking: return "Social Networking"
        case .sports: return "Sports"
        case .travel: return "Travel"
        case .utilities: return "Utilities"
        case .video: return "Video"
        case .weather: return "Weather"
        }
    }
}

public enum PresetColor: String, CaseIterable, Identifiable, Sendable {
    case red = "red"
    case orange = "orange"
    case yellow = "yellow"
    case green = "green"
    case mint = "mint"
    case teal = "teal"
    case cyan = "cyan"
    case blue = "blue"
    case indigo = "indigo"
    case purple = "purple"
    case pink = "pink"
    case brown = "brown"
    
    public var id: String { rawValue }
    
    public var displayName: String {
        switch self {
        case .red: return "Red"
        case .orange: return "Orange"
        case .yellow: return "Yellow"
        case .green: return "Green"
        case .mint: return "Mint"
        case .teal: return "Teal"
        case .cyan: return "Cyan"
        case .blue: return "Blue"
        case .indigo: return "Indigo"
        case .purple: return "Purple"
        case .pink: return "Pink"
        case .brown: return "Brown"
        }
    }
}
